Implement docker build/push in CICD
NASA-PDS/registry-sweepers pull request #7
Opened 2023-04-26 22:32 UTC by alexdunnjpl

## ⚙️ Test Data and/or Report
n/a

## ♻️ Related Issues
fixes #6

2023-04-26 22:44 UTC, merged

2023-04-26 22:44 UTC, nutjob4life commented on .github/workflows/stable-cicd.yaml
> +              name: 🧱 Image Construction and Publication
Indentation looks a little off here (previously 4 spaces, suddenly 2). Not a deal-breaker, though.

2023-04-26 22:45 UTC, nutjob4life requested changes

2023-04-26 22:45 UTC, nutjob4life commented on .github/workflows/stable-cicd.yaml
> +                  tags: ${{secrets.DOCKERHUB_USERNAME}}/registry-api-sweepers:latest
Can we get a version number here instead of `:latest`?

2023-04-26 22:45 UTC, nutjob4life commented on .github/workflows/unstable-cicd.yaml
> +              name: 🧱 Image Construction and Publication
Same indentation issue

2023-04-27 02:02 UTC, alexdunnjpl commented
@nutjob4life so you don't think I'm totally crazy, this'll all get ironed out as I finish it - I opened the PR before I realized I should just do it all on `main` and revert later.